kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployment
spec:
   replicas: 2
   selector:     
    matchLabels:
     app: myspringbootapp
   template:
      metadata:
        labels:
          app: myspringbootapp
      spec:
       containers:
        - name: myspringbootapp
          image: vikashashoke/sringbootapp:latest              # Docker Image we pushed to dockerHub now using here the same..
          imagePullPolicy: Always
          ports:
          - containerPort: 80
