kind: Service                             
apiVersion: v1
metadata:
  name: myservice
  labels:
    app: myspringbootapp
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: myspringbootapp                    
  type: LoadBalancer 
